import org.junit.jupiter.api.Test
import xyz.xenondevs.invui.gui.PagedGui
import xyz.xenondevs.invui.gui.ScrollGui
import xyz.xenondevs.invui.gui.TabGui
import xyz.xenondevs.invui.inventory.Inventory
import xyz.xenondevs.invui.item.Item
import xyz.xenondevs.invui.window.AnvilWindow
import xyz.xenondevs.invui.window.CartographyWindow
import xyz.xenondevs.invui.window.CrafterWindow
import xyz.xenondevs.invui.window.MerchantWindow
import xyz.xenondevs.invui.window.RecipeBookPowered
import xyz.xenondevs.invui.window.StonecutterWindow
import xyz.xenondevs.invui.window.Window

/**
 * Tests for the presence of property accessors.
 * Property accessors are not generated by Kotlin if the types of getter and setter are not the same.
 * This can easily happen accidentally, for example due to mismatched nullability annotations or bounded wildcards
 * for types which do not have declaration-site variance in Kotlin.
 * (i.e. Java List<? extends Item> is List<Item> in Kotlin, but Consumer<? super Integer> is not Consumer<Integer> in Kotlin)
 * 
 * These tests do not run any code, instead they just check that it compiles.
 */
class PropertyAccessorsPresenceTest {

    private lateinit var pagedGui: PagedGui<Item>
    private lateinit var scrollGui: ScrollGui<Item>
    private lateinit var tabGui: TabGui
    private lateinit var inventory: Inventory
    private lateinit var anvilWindow: AnvilWindow
    private lateinit var cartographyWindow: CartographyWindow
    private lateinit var crafterWindow: CrafterWindow
    private lateinit var merchantWindow: MerchantWindow
    private lateinit var recipeBookPowered: RecipeBookPowered
    private lateinit var stonecutterWindow: StonecutterWindow
    private lateinit var window: Window
    
    @Suppress("UnusedLambdaExpression")
    @Test
    fun verifyPresenceOfPropertyAccessors() {
        {
            // -- PagedGui --
            pagedGui.contentListSlots
            pagedGui.contentListSlots = emptyList()
            
            pagedGui.content
            pagedGui.content = emptyList()
            
            pagedGui.pageChangeHandlers
            pagedGui.pageChangeHandlers = emptyList()
            
            pagedGui.pageCountChangeHandlers
            pagedGui.pageCountChangeHandlers = emptyList()
            
            // -- ScrollGui --
            scrollGui.contentListSlots
            // scrollGui.contentListSlots has no direct setter, instead it distinguishes between horizontal / vertical
            
            scrollGui.content
            scrollGui.content = emptyList()
            
            scrollGui.scrollHandlers
            scrollGui.scrollHandlers = emptyList()
            
            // -- TabGui --
            tabGui.contentListSlots
            tabGui.contentListSlots = emptyList()
            
            tabGui.tabs
            tabGui.tabs = emptyList()
            
            tabGui.tabChangeHandlers
            tabGui.tabChangeHandlers = emptyList()
            
            // -- Inventory --
            inventory.clickHandlers
            inventory.clickHandlers = emptyList()
            
            inventory.preUpdateHandlers
            inventory.preUpdateHandlers = emptyList()
            
            inventory.postUpdateHandlers
            inventory.postUpdateHandlers = emptyList()
            
            // -- AnvilWindow --
            anvilWindow.renameHandlers
            anvilWindow.renameHandlers = emptyList()
            
            // -- CartographyWindow --
            cartographyWindow.icons
            cartographyWindow.icons = emptySet()
            
            // -- CrafterWindow --
            crafterWindow.slotToggleHandlers
            crafterWindow.slotToggleHandlers = emptyList()
            
            // -- MerchantWindow --
            merchantWindow.trades
            merchantWindow.trades = emptyList()
        
            // -- RecipeBookPowered --
            recipeBookPowered.recipeClickHandlers
            recipeBookPowered.recipeClickHandlers = emptyList()
            
            // -- StonecutterWindow --
            stonecutterWindow.selectedSlotChangeHandlers
            stonecutterWindow.selectedSlotChangeHandlers = emptyList()
            
            // -- Window --
            window.openHandlers
            window.openHandlers = emptyList()
            
            window.closeHandlers
            window.closeHandlers = emptyList()
            
            window.outsideClickHandlers
            window.outsideClickHandlers = emptyList()
            
            window.windowStateChangeHandlers
            window.windowStateChangeHandlers = emptyList()
        }
    }
    
    private fun <T> emptySequencedSet() = LinkedHashSet<T>()
    
}